### PR TITLE
deleted brotein root dir

### PR DESCRIPTION
**Pull request by Daru233**
testing out pr

### CODE REVIEW

**Review by lazzy-77 — APPROVED** [review]
good stuff

**Review by swaggyC1738 — APPROVED** [review]
yes

**Comment by swaggyC1738** [comment]
class

**Review by swaggyC1738 — APPROVED** [review]
unreal

**Review by swaggyC1738 — APPROVED** [review]

**Review by swaggyC1738 — APPROVED** [review]

**Review by swaggyC1738 — APPROVED** [review]

**Pull request merged**
